spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true  # 이 설정은 동일한 이름을 가진 스프링 빈이 등록되려고 하면 BeanDefinitionOverrideException을 발생
  datasource:
    url: jdbc:h2:tcp://localhost/~/Team_Launch_GOGO;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true   # 이 옵션은 정적 파일 변동 시 자동 반영될 수 있도록 돕는다.
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create  # 이 옵션은 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  file: ./log/local
#spring.profiles.active=pointcut